 # Using docker socket on docker runner
# image: docker:latest
# variables:
#   DOCKER_HOST: 127.0.0.1:2375
#   privileged: 'true'
# services:
#   - docker:dind

stages:
  - docker-build
  - deploy-cloud
  - cleanup-cloud
  - destroy-cloud

provisioning:
  stage: docker-build
  script:
    - docker login -u "gitlab-ci-token" -p "$CI_JOB_TOKEN" $CI_REGISTRY
    - docker build --pull -t "$CI_REGISTRY_IMAGE/$CI_JOB_NAME:$CI_COMMIT_REF_SLUG" .
    - docker push "$CI_REGISTRY_IMAGE/$CI_JOB_NAME:$CI_COMMIT_REF_SLUG"

deploy_cloud:
  image: ${CI_REGISTRY_IMAGE}/provisioning:$CI_COMMIT_REF_SLUG
  stage: deploy-cloud
  only:
    - triggers
  environment:
    name: ${PROJECT}-${CLOUD}
    url: https://$CI_ENVIRONMENT_SLUG.cncf.ci/
    on_stop: destroy_aws_cloud
  artifacts:
    when: always
    expire_in: 4 weeks
    name: "${CI_ENVIRONMENT_SLUG}"
    paths:
    - ./data/
  script:
    - ./provision.sh ${CLOUD}-deploy ${CI_ENVIRONMENT_SLUG}
    - export KUBECONFIG=$(pwd)/data/${CI_ENVIRONMENT_SLUG}/kubeconfig
    - kubectl create -f dns.yaml
    - helm init
    - helm repo add cncf https://cncf.gitlab.io
    - sleep 20 # Wait for Tiller POD
    - helm install --name aws-$(echo ${CI_COMMIT_SHA} | cut -c -5) --set runners.privileged=true --set concurrent=100 --set gitlabUrl=https://gitlab.cncf.ci/ci,runnerRegistrationToken=${GITLAB_REGISTRATION_TOKEN} --set cloud=aws --set commit=${CI_COMMIT_SHA} cncf/gitlab-runner

cleanup_fail:
  image: ${CI_REGISTRY_IMAGE}/provisioning:$CI_COMMIT_REF_SLUG
  stage: cleanup-cloud
  only:
    - triggers
  when: on_failure
  environment:
    name: ${PROJECT}-${CLOUD}
    url: https://$CI_ENVIRONMENT_SLUG.cncf.ci/
    action: stop
  artifacts:
    when: always
    expire_in: 4 weeks
    name: "${CI_ENVIRONMENT_SLUG}"
    paths:
    - ./data/
  script:
    - ./provision.sh ${CLOUD}-destroy ${CI_ENVIRONMENT_SLUG}

cleanup_gke_fail:
  image: ${CI_REGISTRY_IMAGE}/provisioning:$CI_COMMIT_REF_SLUG
  stage: cleanup-clouds
  only:
    - triggers
  when: on_failure
  environment:
    name: ${PROJECT}-${CLOUD}
    url: https://$CI_ENVIRONMENT_SLUG.cncf.ci/
    action: stop
  artifacts:
    when: always
    expire_in: 4 weeks
    name: "${CI_ENVIRONMENT_SLUG}"
    paths:
    - ./data/
  script:
    - ./provision.sh ${CLOUD}-destroy ${CI_ENVIRONMENT_SLUG}
