 # Using docker socket on docker runner
# image: docker:latest
# variables:
#   DOCKER_HOST: 127.0.0.1:2375
#   privileged: 'true'
# services:
#   - docker:dind

stages:
  - docker-build
  - deploy-cloud
  - share-cloud
  - cleanup-cloud
  - destroy-cloud
  # - endpoint-auth

provisioning:
  stage: docker-build
  except:
    - triggers
  script:
    - docker login -u "gitlab-ci-token" -p "$CI_JOB_TOKEN" $CI_REGISTRY
    - docker build --pull -t "$CI_REGISTRY_IMAGE/$CI_JOB_NAME:$CI_COMMIT_REF_SLUG" .
    - docker push "$CI_REGISTRY_IMAGE/$CI_JOB_NAME:$CI_COMMIT_REF_SLUG"

deploy_cloud:
  image: ${CI_REGISTRY_IMAGE}/provisioning:$CI_COMMIT_REF_SLUG
  stage: deploy-cloud
  only:
    - triggers
  environment:
    name: ${PROJECT}-${CLOUD}
    url: https://$CI_ENVIRONMENT_SLUG.cncf.ci/
    on_stop: destroy_cloud
  artifacts:
    when: always
    expire_in: 4 weeks
    name: "${CI_ENVIRONMENT_SLUG}"
    paths:
    - ./data/
  script:
    - ./provision.sh ${CLOUD}-deploy ${CI_ENVIRONMENT_SLUG}
    - export KUBECONFIG=$(pwd)/data/${CI_ENVIRONMENT_SLUG}/kubeconfig
    - if [ $CLOUD != gke ] ; then kubectl create -f dns.yaml ; fi

share_cloud:
  image: ${CI_REGISTRY_IMAGE}/provisioning:$CI_COMMIT_REF_SLUG
  stage: share-cloud
  only:
    - triggers
  environment:
    name: ${PROJECT}-${CLOUD}
    url: https://$CI_ENVIRONMENT_SLUG.cncf.ci/
    on_stop: destroy_cloud
  artifacts:
    when: always
    expire_in: 4 weeks
    name: "${CI_ENVIRONMENT_SLUG}"
    paths:
    - ./data/
  script:
    - export KUBECONFIG=$(pwd)/data/${CI_ENVIRONMENT_SLUG}/kubeconfig
    - sleep 99999999
    - if [ $CLOUD != gke ] ; then kubectl create -f dns.yaml ; fi

cleanup_fail:
  image: ${CI_REGISTRY_IMAGE}/provisioning:$CI_COMMIT_REF_SLUG
  stage: cleanup-cloud
  only:
    - triggers
  when: on_failure
  environment:
    name: ${PROJECT}-${CLOUD}
    url: https://$CI_ENVIRONMENT_SLUG.cncf.ci/
    action: stop
  artifacts:
    when: always
    expire_in: 4 weeks
    name: "${CI_ENVIRONMENT_SLUG}"
    paths:
    - ./data/
  script:
    - ./provision.sh ${CLOUD}-destroy ${CI_ENVIRONMENT_SLUG}
    
destroy_cloud:
  image: ${CI_REGISTRY_IMAGE}/provisioning:$CI_COMMIT_REF_SLUG
  stage: destroy-cloud
  when: manual
  only:
    - triggers
  environment:
    name: ${PROJECT}-${CLOUD}
    url: https://$CI_ENVIRONMENT_SLUG.cncf.ci/
    action: stop
  artifacts:
    when: always
    expire_in: 4 weeks
    name: "${CI_ENVIRONMENT_SLUG}"
    paths:
    - ./data/
  script:
    - ./provision.sh ${CLOUD}-destroy ${CI_ENVIRONMENT_SLUG}
    
# k8s_endpoint:
#   stage: endpoint-auth
#   artifacts:
#     when: always
#     expire_in: 4 weeks
#     name: "${CI_ENVIRONMENT_SLUG}"
#     paths:
#     - ./data/
#   script:
#     - docker login -u "gitlab-ci-token" -p "$CI_JOB_TOKEN" $CI_REGISTRY
#     - docker build --pull -t "$CI_REGISTRY_IMAGE/$CI_JOB_NAME:$CI_COMMIT_REF_SLUG" -f Dockerfile-auth .
#     - docker push "$CI_REGISTRY_IMAGE/$CI_JOB_NAME:$CI_COMMIT_REF_SLUG"

