#These should/can be set via a trigger
variables:
  TF_VAR_kubelet_image_url: "gcr.io/google-containers/hyperkube"
  TF_VAR_kubelet_image_tag: "v1.6.3"

stages:
  - docker-build
  - deploy-cloud
  - destroy-cloud
  
provisioning:
  stage: docker-build
  except:
    - triggers
  script:
    - docker login -u "gitlab-ci-token" -p "$CI_JOB_TOKEN" $CI_REGISTRY
    - docker build --pull -t "$CI_REGISTRY_IMAGE/$CI_JOB_NAME:$CI_COMMIT_REF_SLUG" .
    - docker push "$CI_REGISTRY_IMAGE/$CI_JOB_NAME:$CI_COMMIT_REF_SLUG"

deploy_cloud:
  image: ${CI_REGISTRY_IMAGE}/provisioning:$CI_COMMIT_REF_SLUG
  stage: deploy-cloud
  only:
    - triggers
  environment:
    name: ${CLOUD}-${CI_COMMIT_REF_SLUG}
    url: https://$CI_ENVIRONMENT_SLUG.cncf.ci/
    on_stop: destroy_cloud
  artifacts:
    when: always
    expire_in: 4 weeks
    name: "${CI_ENVIRONMENT_SLUG}"
    paths:
    - ./data/
  script:
    - ./provision.sh ${CLOUD}-deploy ${CI_ENVIRONMENT_SLUG}
    - export KUBECONFIG=$(pwd)/data/${CI_ENVIRONMENT_SLUG}/kubeconfig
    
    
destroy_cloud:
  image: ${CI_REGISTRY_IMAGE}/provisioning:$CI_COMMIT_REF_SLUG
  stage: destroy-cloud
  when: manual
  only:
    - triggers
  environment:
    name: ${CLOUD}-${CI_COMMIT_REF_SLUG}
    url: https://$CI_ENVIRONMENT_SLUG.cncf.ci/
    action: stop
  artifacts:
    when: always
    expire_in: 4 weeks
    name: "${CI_ENVIRONMENT_SLUG}"
    paths:
    - ./data/
  script:
    - ./provision.sh ${CLOUD}-destroy ${CI_ENVIRONMENT_SLUG}



