stages:
  - project-artifacts
  - deploy-k8s
  - e2e-k8s
  - deploy-coredns
  - e2e-coredns
  - deploy-prometheus
  - e2e-prometheus
  - destroy-clouds

before_script:
  - export BASE_URL=${BASE_URL:-$(echo $CI_PROJECT_URL |  cut -d'/' -f1-3)}
  - export KUBECONFIG=$(pwd)/data/${CI_ENVIRONMENT_SLUG}/kubeconfig
  - if [ -d data ] ; then . data/*vars ; fi

kubernetes:
  variables:
    K8S_BRANCH: ci-v1.6.3
  image: ${CI_REGISTRY}/cncf/cross-cloud/provisioning:$CI_COMMIT_REF_SLUG
  stage: project-artifacts
  script:
    - KUBERNETES_RELEASE_VARS=$(curl -L
        "$BASE_URL/kubernetes/kubernetes/builds/artifacts/${K8S_BRANCH}/file/ci.vars?job=build"
        |  sed -n 's/.*href="\([^"]*\).*/\1/p' | grep artifacts/raw | tail -1)
    - mkdir -p data
    - curl -o data/kubernetes.vars -L ${BASE_URL}/$KUBERNETES_RELEASE_VARS
    - cat data/kubernetes.vars
    - KUBERNETES_TAG=$(grep image_tag data/kubernetes.vars | awk -F= '{print $2}')
    - echo "kubernetes release - $KUBERNETES_TAG"
  artifacts:
    when: always
    expire_in: 4 weeks
    paths:
      - ./data/

coredns:
  variables:
    COREDNS_BRANCH: ci-v007
  image: ${CI_REGISTRY}/cncf/cross-cloud/provisioning:$CI_COMMIT_REF_SLUG
  stage: project-artifacts
  script:
    - COREDNS_RELEASE_PROPERTIES=$(curl -L
        "$BASE_URL/coredns/coredns/builds/artifacts/${COREDNS_BRANCH}/file/release.properties?job=release"
        |  sed -n 's/.*href="\([^"]*\).*/\1/p' | grep artifacts/raw | tail -1)
    - mkdir -p data
    - curl -o data/coredns.properties -L ${BASE_URL}/$COREDNS_RELEASE_PROPERTIES
    - cat data/coredns.properties
    - COREDNS_TAG=$(grep image.tag data/coredns.properties  | awk -F= '{print $2}')
    - echo "coredns release - $COREDNS_TAG"
  artifacts:
    when: always
    expire_in: 4 weeks
    paths:
      - ./data/

prometheus:
  variables:
    PROMETHEUS_BRANCH: ci-v1.6.3
  image: ${CI_REGISTRY}/cncf/cross-cloud/provisioning:$CI_COMMIT_REF_SLUG
  stage: project-artifacts
  script:
    - PROMETHEUS_RELEASE_PROPERTIES=$(curl -L
        "$BASE_URL/prometheus/prometheus/builds/artifacts/${PROMETHEUS_BRANCH}/file/release.properties?job=release"
        |  sed -n 's/.*href="\([^"]*\).*/\1/p' | grep artifacts/raw | tail -1)
    - mkdir -p data
    - curl -o data/prometheus.properties -L ${BASE_URL}/$PROMETHEUS_RELEASE_PROPERTIES
    - cat data/prometheus.properties
    - PROMETHEUS_TAG=$(grep image.tag data/prometheus.properties  | awk -F= '{print $2}')
    - echo "prometheus release - $PROMETHEUS_TAG"
  artifacts:
    when: always
    expire_in: 4 weeks
    paths:
      - ./data/

cross-cloud:
  stage: project-artifacts
  script:
    - docker login -u "gitlab-ci-token" -p "$CI_JOB_TOKEN" $CI_REGISTRY
    - docker build --pull -t "$CI_REGISTRY_IMAGE/$CI_JOB_NAME:$CI_COMMIT_REF_SLUG" .
    - docker push "$CI_REGISTRY_IMAGE/$CI_JOB_NAME:$CI_COMMIT_REF_SLUG"

k8s_deploy_aws:
  allow_failure: true
  image: ${CI_REGISTRY}/cncf/cross-cloud/provisioning:$CI_COMMIT_REF_SLUG
  stage: deploy-k8s
  when: manual
  variables:
    CLOUD: aws
  environment:
    name: ${CLOUD}-${CI_COMMIT_REF_SLUG}
    url: https://$CI_ENVIRONMENT_SLUG.cncf.ci/
    on_stop: destroy_aws
  script:
    - /cncf/provision.sh ${CLOUD}-deploy ${CI_ENVIRONMENT_SLUG}
  artifacts:
    when: always
    expire_in: 4 weeks
    paths:
      - ./data/

k8s_e2e_aws:
  image: ${CI_REGISTRY}/kubernetes/kubernetes/kubernetes-e2e:ci-v1-6-3.job.4793
  stage: e2e-k8s
  when: manual
  dependencies:
    - k8s_deploy_aws
  variables:
    CLOUD: aws
  environment:
    name: ${CLOUD}-${CI_COMMIT_REF_SLUG}
    url: https://$CI_ENVIRONMENT_SLUG.demo.cncf.ci/
    on_stop: destroy_aws
  script:
  - export KUBECONFIG=$(pwd)/data/${CI_ENVIRONMENT_SLUG}/kubeconfig
  - DEPLOYED_HYPERKUBE_IMAGE="$(kubectl describe pods  --namespace=kube-system  | grep cncf.ci| grep -v ID| uniq | awk '{print $2}')"
  - echo Deployed HyperKube Image - $DEPLOYED_HYPERKUBE_IMAGE
  - /kubernetes/e2e/run-conformance.sh

coredns_deploy_aws:
  allow_failure: true
  image: ${CI_REGISTRY}/cncf/cross-cloud/provisioning:$CI_COMMIT_REF_SLUG
  stage: deploy-coredns
  when: manual
  dependencies:
    - k8s_deploy_aws
  variables:
    CLOUD: aws
  environment:
    name: ${CLOUD}-${CI_COMMIT_REF_SLUG}
    url: https://$CI_ENVIRONMENT_SLUG.demo.cncf.ci/
    on_stop: destroy_aws
  script:
    - find ./data/
    - ls -la $(pwd)/data/${CI_ENVIRONMENT_SLUG}/
    - kubectl get nodes
    - kubectl get pods
    - kubectl get componentstatuses
    - helm init
    - echo Removing any previous deploys of coredns
    - helm get coredns > /dev/null && helm delete --purge coredns
    - COREDNS_IMAGE_SETTINGS=$(cat data/coredns.properties
        | xargs -n 1 echo \ --set |  awk '!/0$/{printf $0} /0$/')
    - COREDNS_INSTALL="helm install --name coredns ${COREDNS_IMAGE_SETTINGS}
        --set middleware.kubernetes.clusterCidr=10.0.0.0/24
        --set middleware.kubernetes.clusterIP=10.0.0.10
        stable/coredns"
    - echo $COREDNS_INSTALL ; $COREDNS_INSTALL
    - DEPLOYED_COREDNS_IMAGE=$(kubectl get pods -l k8s-app=coredns -o jsonpath="{.items[0].spec.containers[0].image}")
    - echo Deployed CoreDNS Image - $DEPLOYED_COREDNS_IMAGE
    - kubectl get svc
    - kubectl get pods

coredns_e2e_aws:
  image: ${CI_REGISTRY}/coredns/coredns/coredns-e2e:ci-v007.job.4744
  stage: e2e-coredns
  when: manual
  dependencies:
    - coredns_deploy_aws
  variables:
    CLOUD: aws
  environment:
    name: ${CLOUD}-${CI_COMMIT_REF_SLUG}
    url: https://$CI_ENVIRONMENT_SLUG.demo.cncf.ci/
    on_stop: destroy_aws
  script:
  - export KUBECONFIG=$(pwd)/data/${CI_ENVIRONMENT_SLUG}/kubeconfig
  - kubectl proxy --port 8080 &
  - kubectl create -f /coredns/e2e/test.yml || true
  - cd /go/src/github.com/coredns/coredns/test
  - go test -v -tags k8s

prometheus_deploy_aws:
  allow_failure: true
  image: ${CI_REGISTRY}/cncf/cross-cloud/provisioning:$CI_COMMIT_REF_SLUG
  stage: deploy-prometheus
  when: manual
  dependencies:
    - k8s_deploy_aws
  variables:
    CLOUD: aws
  environment:
    name: ${CLOUD}-${CI_COMMIT_REF_SLUG}
    url: https://$CI_ENVIRONMENT_SLUG.demo.cncf.ci/
    on_stop: destroy_aws
  script:
    - find ./data/
    - ls -la $(pwd)/data/${CI_ENVIRONMENT_SLUG}/
    - kubectl get nodes
    - kubectl get pods
    - kubectl get componentstatuses
    - helm init
    - echo Removing any previous deploys of prometheus
    - helm get prometheus > /dev/null && helm delete --purge prometheus
    - PROMETHEUS_IMAGE_SETTINGS=$(cat data/prometheus.properties
        | xargs -n 1 echo \ --set |  awk '!/0$/{printf $0} /0$/')
    - PROMETHEUS_INSTALL="helm install --name prometheus ${PROMETHEUS_IMAGE_SETTINGS}
        stable/prometheus"
    - echo $PROMETHEUS_INSTALL ; $PROMETHEUS_INSTALL
    - DEPLOYED_COREDNS_IMAGE=$(kubectl get pods -l k8s-app=coredns -o jsonpath="{.items[0].spec.containers[0].image}")
    - DEPLOYED_HYPERKUBE_IMAGE="$(kubectl describe pods  --namespace=kube-system  | grep cncf.ci| grep -v ID| uniq | awk '{print $2}')"
    - echo Deployed HyperKube Image - $DEPLOYED_HYPERKUBE_IMAGE
    - echo Deployed CoreDNS Image - $DEPLOYED_COREDNS_IMAGE
    - kubectl get svc
    - kubectl get pods

prometheus_e2e_aws:
  image: ${CI_REGISTRY}/coredns/coredns/coredns-e2e:ci-v007.job.4744
  stage: e2e-prometheus
  when: manual
  dependencies:
    - prometheus_deploy_aws
  variables:
    CLOUD: aws
  environment:
    name: ${CLOUD}-${CI_COMMIT_REF_SLUG}
    url: https://$CI_ENVIRONMENT_SLUG.demo.cncf.ci/
    on_stop: destroy_aws
  script:
  - export KUBECONFIG=$(pwd)/data/${CI_ENVIRONMENT_SLUG}/kubeconfig
  - echo FIXME && exit 1

destroy_aws:
  allow_failure: true
  image: ${CI_REGISTRY}/cncf/cross-cloud/provisioning:$CI_COMMIT_REF_SLUG
  stage: destroy-clouds
  when: manual
  variables:
    CLOUD: aws
  environment:
    name: ${CLOUD}-${CI_COMMIT_REF_SLUG}
    url: https://$CI_ENVIRONMENT_SLUG.demo.cncf.ci/
    action: stop
  script:
    - /cncf/provision.sh ${CLOUD}-destroy ${CI_ENVIRONMENT_SLUG}

deploy_gke:
  allow_failure: true
  image: ${CI_REGISTRY}/cncf/cross-cloud/provisioning:$CI_COMMIT_REF_SLUG
  stage: deploy-k8s
  when: manual
  variables:
    CLOUD: gke
  environment:
    name: ${CLOUD}-${CI_COMMIT_REF_SLUG}
    url: https://$CI_ENVIRONMENT_SLUG.cncf.ci/
    on_stop: destroy_gke
  script:
    - /cncf/provision.sh ${CLOUD}-deploy ${CI_ENVIRONMENT_SLUG}
  artifacts:
    when: always
    expire_in: 4 weeks
    paths:
      - ./data/

# use_gke:
#   allow_failure: true
#   image: ${CI_REGISTRY}/cncf/cross-cloud/provisioning:$CI_COMMIT_REF_SLUG
#   stage: use-clouds
#   when: manual
#   dependencies:
#     - deploy_gke
#   variables:
#     CLOUD: gke
#   environment:
#     name: ${CLOUD}-${CI_COMMIT_REF_SLUG}
#     url: https://$CI_ENVIRONMENT_SLUG.demo.cncf.ci/
#     on_stop: destroy_gke
#   script:
#     - export KUBECONFIG=$(pwd)/data/${CI_ENVIRONMENT_SLUG}/kubeconfig
#     - kubectl get nodes
#     - kubectl get pods
#     - kubectl get componentstatuses

# destroy_gke:
#   allow_failure: true
#   image: ${CI_REGISTRY}/cncf/cross-cloud/provisioning:$CI_COMMIT_REF_SLUG
#   stage: destroy-clouds
#   when: manual
#   variables:
#     CLOUD: gke
#   environment:
#     name: ${CLOUD}-${CI_COMMIT_REF_SLUG}
#     url: https://$CI_ENVIRONMENT_SLUG.demo.cncf.ci/
#     action: stop
#   script:
#     - /cncf/provision.sh ${CLOUD}-destroy ${CI_ENVIRONMENT_SLUG}

# deploy_azure:
#   allow_failure: true
#   image: ${CI_REGISTRY}/cncf/cross-cloud/provisioning:$CI_COMMIT_REF_SLUG
#   stage: deploy-k8s
#   when: manual
#   variables:
#     CLOUD: azure
#   environment:
#     name: ${CLOUD}-${CI_COMMIT_REF_SLUG}
#     url: https://$CI_ENVIRONMENT_SLUG.cncf.ci/
#     on_stop: destroy_gke
#   script:
#     - /cncf/provision.sh ${CLOUD}-deploy ${CI_ENVIRONMENT_SLUG}
#   artifacts:
#     when: always
#     expire_in: 4 weeks
#     paths:
#       - ./data/

# use_azure:
#   allow_failure: true
#   image: ${CI_REGISTRY}/cncf/cross-cloud/provisioning:$CI_COMMIT_REF_SLUG
#   stage: use-clouds
#   when: manual
#   dependencies:
#     - deploy_azure
#   variables:
#     CLOUD: azure
#   environment:
#     name: ${CLOUD}-${CI_COMMIT_REF_SLUG}
#     url: https://$CI_ENVIRONMENT_SLUG.demo.cncf.ci/
#     on_stop: destroy_gke
#   script:
#     - kubectl get nodes
#     - kubectl get pods
#     - kubectl get componentstatuses

# destroy_azure:
#   allow_failure: true
#   image: ${CI_REGISTRY}/cncf/cross-cloud/provisioning:$CI_COMMIT_REF_SLUG
#   stage: destroy-clouds
#   when: manual
#   variables:
#     CLOUD: azure
#   environment:
#     name: ${CLOUD}-${CI_COMMIT_REF_SLUG}
#     url: https://$CI_ENVIRONMENT_SLUG.demo.cncf.ci/
#     action: stop
#   script:
#     - /cncf/provision.sh ${CLOUD}-destroy ${CI_ENVIRONMENT_SLUG}

# deploy_packet:
#   allow_failure: true
#   image: ${CI_REGISTRY}/cncf/cross-cloud/provisioning:$CI_COMMIT_REF_SLUG
#   stage: deploy-k8s
#   when: manual
#   variables:
#     CLOUD: packet
#   environment:
#     name: ${CLOUD}-${CI_COMMIT_REF_SLUG}
#     url: https://$CI_ENVIRONMENT_SLUG.cncf.ci/
#     on_stop: destroy_packet
#   script:
#     - /cncf/provision.sh ${CLOUD}-deploy ${CI_ENVIRONMENT_SLUG}
#   artifacts:
#     when: always
#     expire_in: 4 weeks
#     paths:
#       - ./data/

# k8s_e2e_packet:
#   image: ${CI_REGISTRY}/kubernetes/kubernetes/kubernetes-e2e:ci-v1-6-3.job.4793
#   stage: e2e-k8s
#   when: manual
#   dependencies:
#     - deploy_packet
#   variables:
#     CLOUD: packet
#   environment:
#     name: ${CLOUD}-${CI_COMMIT_REF_SLUG}
#     url: https://$CI_ENVIRONMENT_SLUG.demo.cncf.ci/
#     on_stop: destroy_aws
#   script:
#   - export KUBECONFIG=$(pwd)/data/${CI_ENVIRONMENT_SLUG}/kubeconfig
#   - /kubernetes/e2e/run-conformance.sh

# use_packet:
#   allow_failure: true
#   image: ${CI_REGISTRY}/cncf/cross-cloud/provisioning:$CI_COMMIT_REF_SLUG
#   stage: use-clouds
#   when: manual
#   dependencies:
#     - deploy_packet
#   variables:
#     CLOUD: packet
#   environment:
#     name: ${CLOUD}-${CI_COMMIT_REF_SLUG}
#     url: https://$CI_ENVIRONMENT_SLUG.demo.cncf.ci/
#     on_stop: destroy_packet
#   script:
#     - export KUBECONFIG=$(pwd)/data/${CI_ENVIRONMENT_SLUG}/kubeconfig
#     - kubectl get nodes
#     - kubectl get pods
#     - kubectl get componentstatuses

# destroy_packet:
#   allow_failure: true
#   image: ${CI_REGISTRY}/cncf/cross-cloud/provisioning:$CI_COMMIT_REF_SLUG
#   stage: destroy-clouds
#   when: manual
#   variables:
#     CLOUD: packet
#   environment:
#     name: ${CLOUD}-${CI_COMMIT_REF_SLUG}
#     url: https://$CI_ENVIRONMENT_SLUG.demo.cncf.ci/
#     action: stop
#   script:
#     - /cncf/provision.sh ${CLOUD}-destroy ${CI_ENVIRONMENT_SLUG}

# deploy_gce:
#   allow_failure: true
#   image: ${CI_REGISTRY}/cncf/cross-cloud/provisioning:$CI_COMMIT_REF_SLUG
#   stage: deploy-k8s
#   when: manual
#   variables:
#     CLOUD: gce
#   environment:
#     name: ${CLOUD}-${CI_COMMIT_REF_SLUG}
#     url: https://$CI_ENVIRONMENT_SLUG.cncf.ci/
#     on_stop: destroy_gce
#   script:
#     - /cncf/provision.sh ${CLOUD}-deploy ${CI_ENVIRONMENT_SLUG}
#   artifacts:
#     when: always
#     expire_in: 4 weeks
#     paths:
#       - ./data/

# use_gce:
#   allow_failure: true
#   image: ${CI_REGISTRY}/cncf/cross-cloud/provisioning:$CI_COMMIT_REF_SLUG
#   stage: use-clouds
#   when: manual
#   dependencies:
#     - deploy_gce
#   variables:
#     CLOUD: gce
#   environment:
#     name: ${CLOUD}-${CI_COMMIT_REF_SLUG}
#     url: https://$CI_ENVIRONMENT_SLUG.demo.cncf.ci/
#     on_stop: destroy_gce
#   script:
#     - kubectl get nodes
#     - kubectl get pods
#     - kubectl get componentstatuses

# destroy_gce:
#   allow_failure: true
#   image: ${CI_REGISTRY}/cncf/cross-cloud/provisioning:$CI_COMMIT_REF_SLUG
#   stage: destroy-clouds
#   when: manual
#   variables:
#     CLOUD: gce
#   environment:
#     name: ${CLOUD}-${CI_COMMIT_REF_SLUG}
#     url: https://$CI_ENVIRONMENT_SLUG.demo.cncf.ci/
#     action: stop
#   script:
#     - /cncf/provision.sh ${CLOUD}-destroy ${CI_ENVIRONMENT_SLUG}

