 # Using docker socket on docker runner
# image: docker:latest
# variables:
#   DOCKER_HOST: 127.0.0.1:2375
#   privileged: 'true'
# services:
#   - docker:dind

stages:
  - docker-builds
  - deploy-clouds
  - cleanup-clouds
  - destroy-clouds

provisioning:
  stage: docker-builds
  script:
    - docker login -u "gitlab-ci-token" -p "$CI_JOB_TOKEN" $CI_REGISTRY
    - docker build --pull -t "$CI_REGISTRY_IMAGE/$CI_JOB_NAME:$CI_COMMIT_REF_SLUG" .
    - docker push "$CI_REGISTRY_IMAGE/$CI_JOB_NAME:$CI_COMMIT_REF_SLUG"

deploy_aws_cloud:
  image: ${CI_REGISTRY_IMAGE}/provisioning:$CI_COMMIT_REF_SLUG
  stage: deploy-clouds
  environment:
    name: $CI_COMMIT_REF_SLUG
    url: https://$CI_ENVIRONMENT_SLUG.cncf.ci/
    on_stop: destroy_aws_cloud
  artifacts:
    when: always
    expire_in: 4 weeks
    name: "${CI_ENVIRONMENT_SLUG}"
    paths:
    - ./data/
  script:
    - export DEPLOY=aws-${CI_ENVIRONMENT_SLUG}-$(echo ${CI_COMMIT_SHA} | cut -c -5)
    - ./provision.sh aws-deploy ${DEPLOY}
    - export KUBECONFIG=$(pwd)/provisioning/data/${DEPLOY}/kubeconfig
    - kubectl create -f /builds/cncf/demo/AddOns/dns.yaml
    - helm init
    - helm repo add cncf https://cncf.gitlab.io
    - sleep 20 # Wait for Tiller POD
    - helm install --name aws-$(echo ${CI_COMMIT_SHA} | cut -c -5) --set runners.privileged=true --set concurrent=100 --set gitlabUrl=https://gitlab.cncf.ci/ci,runnerRegistrationToken=${GITLAB_REGISTRATION_TOKEN} --set cloud=aws --set commit=${CI_COMMIT_SHA} cncf/gitlab-runner

deploy_gke_cloud:
  image: ${CI_REGISTRY}/cncf/demo/provisioning:$CI_COMMIT_REF_SLUG
  stage: deploy-clouds
  environment:
    name: $CI_COMMIT_REF_SLUG
    url: https://$CI_ENVIRONMENT_SLUG.cncf.ci/
    on_stop: destroy_gke_cloud
  artifacts:
    when: always
    expire_in: 4 weeks
    name: "${CI_ENVIRONMENT_SLUG}"
    paths:
    - ./data/
  script:
    - export DEPLOY=gke-${CI_ENVIRONMENT_SLUG}-$(echo ${CI_COMMIT_SHA} | cut -c -5)
    - ./provision.sh gke-deploy ${DEPLOY}
    - export KUBECONFIG=$(pwd)/provisioning/data/${DEPLOY}/kubeconfig
    - kubectl create -f /builds/cncf/demo/AddOns/dns.yaml
    - helm init
    - helm repo add cncf https://cncf.gitlab.io
    - sleep 20 # Wait for Tiller POD
    - helm install --name gke-$(echo ${CI_COMMIT_SHA} | cut -c -5) --set runners.privileged=true --set concurrent=100 --set gitlabUrl=https://gitlab.cncf.ci/ci,runnerRegistrationToken=${GITLAB_REGISTRATION_TOKEN} --set cloud=gke --set commit=${CI_COMMIT_SHA} cncf/gitlab-runner
    
cleanup_aws_fail:
  image: ${CI_REGISTRY}/cncf/demo/provisioning:$CI_COMMIT_REF_SLUG
  stage: cleanup-clouds
  when: on_failure
  environment:
    name: $CI_COMMIT_REF_SLUG
    url: https://$CI_ENVIRONMENT_SLUG.cncf.ci/
    action: stop
  artifacts:
    when: always
    expire_in: 4 weeks
    name: "${CI_ENVIRONMENT_SLUG}"
    paths:
    - ./data/
  script:
    - export DEPLOY=aws-${CI_ENVIRONMENT_SLUG}-$(echo ${CI_COMMIT_SHA} | cut -c -5)
    - ./provision.sh aws-destroy ${DEPLOY}
    
cleanup_gke_fail:
  image: ${CI_REGISTRY}/cncf/demo/provisioning:$CI_COMMIT_REF_SLUG
  stage: cleanup-clouds
  when: on_failure
  environment:
    name: $CI_COMMIT_REF_SLUG
    url: https://$CI_ENVIRONMENT_SLUG.cncf.ci/
    action: stop
  artifacts:
    when: always
    expire_in: 4 weeks
    name: "${CI_ENVIRONMENT_SLUG}"
    paths:
    - ./data/
  script:
    - export DEPLOY=gke-${CI_ENVIRONMENT_SLUG}-$(echo ${CI_COMMIT_SHA} | cut -c -5)
    - ./provision.sh gke-destroy ${DEPLOY}

destroy_aws_cloud:
  image: ${CI_REGISTRY}/cncf/demo/provisioning:$CI_COMMIT_REF_SLUG
  stage: destroy-clouds
  when: manual
  environment:
    name: $CI_COMMIT_REF_SLUG
    url: https://$CI_ENVIRONMENT_SLUG.cncf.ci/
    action: stop
  artifacts:
    when: always
    expire_in: 4 weeks
    name: "${CI_ENVIRONMENT_SLUG}"
    paths:
    - ./data/
  script:
    - export DEPLOY=aws-{CI_ENVIRONMENT_SLUG}-$(echo ${CI_COMMIT_SHA} | cut -c -5)
    - ./provision.sh aws-destroy ${DEPLOY}
    
destroy_gke_cloud:
  image: ${CI_REGISTRY}/cncf/demo/provisioning:$CI_COMMIT_REF_SLUG
  stage: destroy-clouds
  when: manual
  environment:
    name: $CI_COMMIT_REF_SLUG
    url: https://$CI_ENVIRONMENT_SLUG.cncf.ci/
    action: stop
  artifacts:
    when: always
    expire_in: 4 weeks
    name: "${CI_ENVIRONMENT_SLUG}"
    paths:
    - ./data/
  script:
    - export DEPLOY=gke-${CI_ENVIRONMENT_SLUG}-$(echo ${CI_COMMIT_SHA} | cut -c -5)
    - ./provision.sh gke-destroy ${DEPLOY}

