apiVersion: v1
kind: Pod
metadata:
  name: kube-apiserver
  namespace: kube-system
spec:
  hostNetwork: true
  containers:
  - name: kube-apiserver
    image: ${ hyperkube }
    command:
    - /hyperkube
    - apiserver
    - --cloud-provider=aws
    - --bind-address=0.0.0.0
    - --etcd-servers=http://etcd.${ internal_tld }:2379
    - --allow-privileged=true
    - --service-cluster-ip-range=${ service_cidr }
    - --secure-port=443
    # FIX?? Unable to use $private_ipv4 because var is unavalible if unset bind adderess is used
    # - --advertise-address=$private_ipv4
    - --admission-control=NamespaceLifecycle,LimitRanger,ServiceAccount,DefaultStorageClass,ResourceQuota
    - --tls-cert-file=/etc/kubernetes/ssl/k8s-apiserver.pem
    - --tls-private-key-file=/etc/kubernetes/ssl/k8s-apiserver-key.pem
    - --client-ca-file=/etc/kubernetes/ssl/ca.pem
    - --service-account-key-file=/etc/kubernetes/ssl/k8s-apiserver-key.pem
    - --runtime-config=extensions/v1beta1/networkpolicies=true
    - --anonymous-auth=false
    - --storage-backend=etcd2
    # Verbose Logging
    - --v=2
    livenessProbe:
      httpGet:
        host: 127.0.0.1
        port: 8080
        path: /healthz
      initialDelaySeconds: 15
      timeoutSeconds: 15
    ports:
    - containerPort: 443
      hostPort: 443
      name: https
    - containerPort: 8080
      hostPort: 8080
      name: local
    volumeMounts:
    - mountPath: /etc/kubernetes/ssl
      name: ssl-certs-kubernetes
      readOnly: true
    - mountPath: /etc/ssl/certs
      name: ssl-certs-host
      readOnly: true
  volumes:
  - hostPath:
      path: /etc/kubernetes/ssl
    name: ssl-certs-kubernetes
  - hostPath:
      path: /usr/share/ca-certificates
    name: ssl-certs-host
