# Default values for coredns.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: coredns/coredns
  tag: "011"
  pullPolicy: IfNotPresent

resources:
  limits:
    cpu: 100m
    memory: 128Mi
  requests:
    cpu: 100m
    memory: 128Mi

# isClusterService specifies whether chart should be deployed as cluster-service or normal k8s app.
isClusterService: false

# serviceType specifies type of service to be created for this chart.
serviceType: "ClusterIP"

# serviceProtocol specifies the protocol on which to expose the CoreDNS service.
# Can be one of three options: "UDPNTCP" (default), "UDP" or "TCP"
serviceProtocol: "UDPNTCP"

# middleware configuration of CoreDNS refer to https://github.com/coredns/coredns/tree/master/middleware
# for all specific details. set enabled to true/false to enable/disable a middleware.
middleware:
  kubernetes:
    enabled: false
    clusterCidr: "10.3.0.0/24"
    clusterDomain: "cluster.local"
    clusterIP:
  log:
    enabled: false
    file: "stdout"
  health:
    enabled: true
  proxy:
    enabled: true
  cache:
    enabled: true
  loadbalance:
    enabled: false
    policy: "round_robin"
  etcd:
    enabled: true
    zones:
      - "gce.local"
    path: "/skydns"
    endpoint: "http://127.0.0.1:4000"
