apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    k8s-app: etcd-server-events
  name: etcd-server-events
  namespace: kube-system
spec:
  containers:
  - command:
    - /bin/sh
    - -c
    - /usr/local/bin/etcd 1>>/var/log/etcd-events.log 2>&1
    env:
    - name: ETCD_NAME
      value: events-${ fqdn }
    - name: ETCD_DATA_DIR
      value: /var/etcd/data-events
    - name: ETCD_LISTEN_PEER_URLS
      value: http://${ fqdn }:2381
    - name: ETCD_LISTEN_CLIENT_URLS
      value: http://${ fqdn }:4002,http://127.0.0.1:4002
    - name: ETCD_ADVERTISE_CLIENT_URLS
      value: http://${ fqdn }:4002
    - name: ETCD_INITIAL_ADVERTISE_PEER_URLS
      value: http://${ fqdn }:2381
    - name: ETCD_DISCOVERY
      value: ${ etcd_events_discovery }
    image: registry.cncf.ci/etcd/etcd-docker:master.38cc76af.26448
    livenessProbe:
      httpGet:
        host: 127.0.0.1
        path: /health
        port: 4002
      initialDelaySeconds: 15
      timeoutSeconds: 15
    name: etcd-container
    ports:
    - containerPort: 2381
      hostPort: 2381
      name: serverport
    - containerPort: 4002
      hostPort: 4002
      name: clientport
    resources:
      requests:
        cpu: 100m
    volumeMounts:
    - mountPath: /var/etcd/data-events
      name: varetcdata
    - mountPath: /var/log
      name: varlogetcd
  hostNetwork: true
  volumes:
  - hostPath:
      path: /var/etcd/data-events
    name: varetcdata
  - hostPath:
      path: /var/log
    name: varlogetcd
status: {}
