apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    k8s-app: etcd-server-events
  name: etcd-server-events
  namespace: kube-system
spec:
  containers:
  - command:
    - /bin/sh
    - -c
    - /usr/local/bin/etcd 1>>/var/log/etcd.log 2>&1
    env:
    - name: ETCD_NAME
      value: events-${ fqdn }
    - name: ETCD_DATA_DIR
      value: /var/etcd/data-events
    - name: ETCD_LISTEN_PEER_URLS
      value: http://${ fqdn }:2381
    - name: ETCD_LISTEN_CLIENT_URLS
      value: http://${ fqdn }:2381,http://127.0.0.1:2381
    - name: ETCD_ADVERTISE_CLIENT_URLS
      value: http://${ fqdn }:2381
    - name: ETCD_INITIAL_ADVERTISE_PEER_URLS
      value: http://${ fqdn }:2382
    - name: ETCD_INITIAL_CLUSTER
      value: ${ etcd_events_discovery }
    image: gcr.io/google_containers/etcd:2.2.1
    livenessProbe:
      httpGet:
        host: 127.0.0.1
        path: /health
        port: 4002
      initialDelaySeconds: 15
      timeoutSeconds: 15
    name: etcd-container
    ports:
    - containerPort: 2381
      hostPort: 2381
      name: serverport
    - containerPort: 4002
      hostPort: 4002
      name: clientport
    resources:
      requests:
        cpu: 100m
    volumeMounts:
    - mountPath: /var/etcd/data-events
      name: varetcdata
    - mountPath: /var/log/etcd.log
      name: varlogetcd
  hostNetwork: true
  volumes:
  - hostPath:
      path: /var/etcd/data-events
    name: varetcdata
  - hostPath:
      path: /var/log/etcd-events.log
    name: varlogetcd
status: {}
