apiVersion: v1
kind: Config
users:
- name: kube-proxy
  user:
    token: ${ TOKEN }
clusters:
- name: local
  cluster:
    certificate-authority-data: ${ CA }
contexts:
- context:
    cluster: local
    user: kube-proxy
  name: service-account-context
current-context: service-account-context
