#cloud-config

---
coreos:

  # etcd2:
  #   discovery-srv: ${ internal_tld }
  #   peer-trusted-ca-file: /etc/kubernetes/ssl/ca.pem
  #   peer-client-cert-auth: true
  #   peer-cert-file: /etc/kubernetes/pki/kubelet.crt
  #   peer-key-file: /etc/kubernetes/ssl/kubelet.key
  #   proxy: on

  units:
    # - name: etcd2.service
      # command: start

    - name: docker.service
      command: start
      drop-ins:
        - name: docker.conf
          content: |
            [Service]
            EnvironmentFile=/etc/default/docker
            # ExecStartPre=/usr/bin/ip link add name cbr0 type bridge

    - name: bins.service
      command: start
      content: |
        [Unit]
        Description=Download Binaries
        [Service]
        Type=oneshot
        RemainAfterExit=yes
        ExecStartPre=/usr/bin/mkdir --parents /opt/cni/bin
        ExecStartPre=/usr/bin/mkdir --parents /etc/cni/net.d
        ExecStartPre=/usr/bin/mkdir --parents /home/kubernetes/bin
        ExecStartPre=/usr/bin/curl -L -o /home/kubernetes/bin/kubelet https://storage.googleapis.com/kubernetes-release/release/v1.7.2/bin/linux/amd64/kubelet
        ExecStartPre=/usr/bin/curl -L -o /tmp/cni.tar https://github.com/containernetworking/cni/releases/download/v0.5.2/cni-amd64-v0.5.2.tgz
        ExecStartPre=/usr/bin/tar -xvf /tmp/cni.tar -C /opt/cni/bin/
        ExecStart=/usr/bin/chmod +x /home/kubernetes/bin/kubelet

    - name: socat.service
      command: start
      content: |
        [Unit]
        Description=Install Socat
        After=docker.service
        Requires=docker.service

        [Service]
        Type=oneshot
        RemainAfterExit=yes
        ExecStartPre=/usr/bin/mkdir --parents /opt/bin
        ExecStart=/usr/bin/docker run --rm -v /opt/bin/:/socat/ registry.cncf.ci/cncf/cross-cloud/socat:ci-stable-v0-2-0 cp /output/linux/x86_64/socat /socat

    - name: kubelet.service
      command: start
      content: |
        [Unit]
        Description=Kubernetes kubelet
        After=socat.service
        Requires=socat.service

        [Service]
        Restart=always
        RestartSec=10
        Environment="PATH=/opt/bin/:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
        EnvironmentFile=/etc/default/kubelet
        ExecStart=/home/kubernetes/bin/kubelet $KUBELET_OPTS

        [Install]
        WantedBy=multi-user.target

  update:
    reboot-strategy: etcd-lock

write-files:

  - path: /etc/default/docker
    content: |
      DOCKER_OPTS="--ip-masq=false --iptables=false --log-driver=json-file --log-level=warn --log-opt=max-file=5 --log-opt=max-size=10m --storage-driver=overlay"

  - path: /etc/default/kubelet
    content: |
      KUBELET_OPTS="--allow-privileged=true --cgroup-root=/ --cloud-provider=azure --cloud-config=/etc/srv/kubernetes/azure-config.json --cluster-dns=${ dns_service_ip } --cluster-domain=${ cluster_domain } --authorization-mode=Webhook --enable-debugging-handlers=true --eviction-hard=memory.available<100Mi,nodefs.available<10%,nodefs.inodesFree<5%,imagefs.available<10%,imagefs.inodesFree<5% --hostname-override=${ fqdn } --kubeconfig=/var/lib/kubelet/kubeconfig --network-plugin-mtu=9001 --network-plugin=kubenet --node-labels=kubernetes.io/role=node --non-masquerade-cidr=${ non_masquerade_cidr } --pod-infra-container-image=gcr.io/google_containers/pause-amd64:3.0 --pod-manifest-path=/etc/kubernetes/manifests --register-schedulable=true --require-kubeconfig=true --v=2 --cni-bin-dir=/opt/cni/bin/ --cni-conf-dir=/etc/cni/net.d/ --network-plugin-dir=/opt/cni/bin/"

  - path: /etc/kubernetes/manifests/kube-proxy.yml
    permissions: "0644"
    encoding: "gzip+base64"
    content: |
      ${ kube_proxy }

  - path: /var/lib/kube-proxy/kubeconfig
    permissions: "0644"
    encoding: "gzip+base64"
    content: |
      ${ proxy_kubeconfig }

  - path: /var/lib/kubelet/kubeconfig
    permissions: "0644"
    encoding: "gzip+base64"
    content: |
      ${ kubelet_kubeconfig }

  - path: /etc/kubernetes/pki/ca-certificates.crt
    permissions: "0644"
    encoding: "gzip+base64"
    content: |
      ${ ca }
      
  - path: /etc/kubernetes/pki/kubelet.crt
    permissions: "0644"
    encoding: "gzip+base64"
    content: |
      ${ worker }
      
  - path: /etc/kubernetes/pki/kubelet.key
    permissions: "0644"
    encoding: "gzip+base64"
    content: |
      ${ worker_key }

  - path: /etc/srv/kubernetes/azure-config.json
    permissions: "0644"
    encoding: "gzip+base64"
    content: |
      ${ azure_cloud }
